### ISSUE TITLE
link to support the claim t3 recommended?

### ISSUE THREAD

**Issue by allan-simon** [jean553/gitlab-runner#1]
would be interested to know if it's you who recommend it or gitlab.com or aws ?

**Comment by jean553** [comment]
Thanks for the issue.

This is definitely a mistake, as there is absolutely no peculiar reason to start the runner with a t3.medium instance type.

I remove completely the documentation section (https://github.com/jean553/gitlab-runner/pull/2/commits/3fdb3bccd4efbc1a8e165dfbe9ea86af3fd84caf). I guess this section should be improved with commands to execute on the runner once the machine is launched.

**Comment by allan-simon** [comment]
ok thanks
